events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name _;
        
        # Xtream Codes API
        location / {
            proxy_pass http://127.0.0.1:25462;
            proxy_set_header Host $host;
        }
        
        # Admin Panel
        location /admin {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
        }
    }
}
